import React, { useContext, useEffect, useState } from 'react'
import { Activity, ArrowUpRight, BarChart3, MousePointer2, Users } from 'lucide-react'
import Layout from '../components/Layout'
import StatCard from '../components/StatCard'
import { supabase } from '../lib/supabase'
import { AppContext } from '../main'
export default function Analytics(){
 const {session,t}=useContext(AppContext); const [stats,setStats]=useState(null); const [events,setEvents]=useState([]); const [loading,setLoading]=useState(true)
 useEffect(()=>{(async()=>{const {data:s}=await supabase.rpc('get_profile_stats',{p_profile_id:session.user.id});setStats(s?.[0]||{visits:0,clicks:0,top_links:[]});const {data:e}=await supabase.from('analytics_events').select('id,event_type,created_at,link:profile_links(title,type)').eq('profile_id',session.user.id).order('created_at',{ascending:false}).limit(20);setEvents(e||[]);setLoading(false)})()},[session.user.id])
 const top=stats?.top_links||[]
 return <Layout><main className="page"><div className="page-header"><div><div className="eyebrow">ELVRA / ANALYTICS</div><h1>{t.analyticsTitle}</h1><p>Visits and link clicks are stored as real Supabase events — not demo counters.</p></div><div className="live-badge"><span className="live-dot"/> LIVE DATA</div></div>{loading?<div className="loading-card shimmer"/>:<><div className="stats-grid"><StatCard label={t.visits} value={stats.visits||0} note="Recorded page views" icon={<Users size={18}/>} /><StatCard label={t.clicks} value={stats.clicks||0} note="Recorded link clicks" icon={<MousePointer2 size={18}/>} /><StatCard label="CTR" value={stats.visits?Math.round((stats.clicks/stats.visits)*100):0} note="Clicks per 100 visits" icon={<BarChart3 size={18}/>} /></div><div className="analytics-grid"><section className="panel"><div className="section-title"><span>{t.topLinks}</span><ArrowUpRight size={16}/></div>{top.length===0?<div className="empty-state"><Activity size={25}/><b>{t.noData}</b><span>Once somebody opens a link from your card, it will appear here.</span></div>:<div className="top-list">{top.map((x,i)=><div className="top-row" key={x.title||i}><span className="rank">0{i+1}</span><div className="top-name"><b>{x.title}</b><small>{x.type}</small></div><div className="top-count">{x.clicks}</div></div>)}</div>}</section><section className="panel"><div className="section-title"><span>{t.recentActivity}</span><Activity size={16}/></div><div className="event-list">{events.length===0?<div className="empty-state"><Activity size={25}/><b>No events yet</b><span>Open your public card and click a link to test tracking.</span></div>:events.map(e=><div className="event-row" key={e.id}><div className={`event-icon ${e.event_type}`}><span>{e.event_type==='visit'?'V':'C'}</span></div><div><b>{e.event_type==='visit'?t.visits:t.clicks}</b><small>{e.link?.title || 'Public profile'}</small></div><time>{new Date(e.created_at).toLocaleString()}</time></div>)}</div></section></div></>}</main></Layout>
}
