import React, { useEffect, useState } from 'react'
import { ExternalLink, Instagram, Link2, Mail, MapPin, Phone, Share2 } from 'lucide-react'
import { useParams } from 'react-router-dom'
import { supabase } from '../lib/supabase'
const iconFor=t=>({instagram:Instagram,phone:Phone,email:Mail,map:MapPin}[t]||Link2)
export default function PublicCard(){
 const {slug}=useParams(); const [data,setData]=useState(null); const [error,setError]=useState(false)
 useEffect(()=>{(async()=>{const {data:d,error:e}=await supabase.rpc('get_public_profile',{p_slug:slug});if(e||!d?.length){setError(true);return}const p=d[0];const {data:links}=await supabase.rpc('get_public_links',{p_profile_id:p.id});setData({...p,links:links||[]});await supabase.rpc('record_profile_event',{p_profile_id:p.id,p_event_type:'visit',p_link_id:null})})()},[slug])
 const click=async(l)=>{if(data?.id) await supabase.rpc('record_profile_event',{p_profile_id:data.id,p_event_type:'click',p_link_id:l.id})}
 if(error)return <div className="public-error"><h1>404</h1><p>This ELVRA card could not be found.</p></div>
 if(!data)return <div className="boot"><div className="boot-mark">E</div><div className="spinner" /></div>
 const accent=data.accent||'#00D084';
 return <div className="public-page" style={{'--accent':accent}}><div className="public-orb one"/><div className="public-orb two"/><div className="public-card"><div className="public-cover" style={{backgroundImage:data.cover_url?`url(${data.cover_url})`:undefined}}/><div className="public-content"><div className="public-avatar">{data.avatar_url?<img src={data.avatar_url} alt=""/>:<span>{data.display_name?.slice(0,1)||'E'}</span>}</div><div className="public-name-row"><div><div className="public-eyebrow">ELVRA DIGITAL IDENTITY</div><h1>{data.display_name}</h1></div><button className="share-btn" onClick={async()=>{if(navigator.share)await navigator.share({title:data.display_name,url:location.href});else await navigator.clipboard.writeText(location.href)}}><Share2 size={18}/></button></div>{data.bio&&<p className="public-bio">{data.bio}</p>}<div className="public-meta">{data.location&&<span><MapPin size={14}/>{data.location}</span>}{data.website&&<a href={data.website.startsWith('http')?data.website:`https://${data.website}`} target="_blank" rel="noreferrer"><ExternalLink size={14}/>Website</a>}</div><div className="public-links">{data.links.map(l=>{const I=iconFor(l.type);return <a className="public-link" key={l.id} href={l.url} target={l.type==='phone'||l.type==='email'?'_self':'_blank'} rel="noreferrer" onClick={()=>click(l)}><span className="public-link-icon"><I size={18}/></span><span><b>{l.title}</b><small>{l.type}</small></span><ExternalLink size={16}/></a>})}</div><div className="public-footer"><span>Powered by <b>ELVRA</b></span><span className="dot" style={{background:accent}}/></div></div></div></div>
}
