import React, { useContext, useState } from 'react'
import { Check, Globe2, LockKeyhole, Moon, Palette, Sun } from 'lucide-react'
import Layout from '../components/Layout'
import { supabase } from '../lib/supabase'
import { AppContext } from '../main'
export default function Settings(){
 const {t,lang,setLang,theme,setTheme}=useContext(AppContext);const[p,setP]=useState('');const[c,setC]=useState('');const[msg,setMsg]=useState('');const[err,setErr]=useState('')
 const update=async e=>{e.preventDefault();setErr('');setMsg('');if(p!==c)return setErr('Passwords do not match.');const {error}=await supabase.auth.updateUser({password:p});if(error)setErr(error.message);else{setMsg(t.passwordUpdated);setP('');setC('')}}
 return <Layout><main className="page"><div className="page-header"><div><div className="eyebrow">ELVRA / SETTINGS</div><h1>{t.settingsTitle}</h1><p>Everything important about your account, language and appearance in one place.</p></div></div><div className="settings-grid"><section className="panel settings-panel"><div className="section-title"><span><Globe2 size={16}/> {t.language}</span></div><div className="setting-option"><div><b>Interface language</b><span>Change the entire dashboard instantly.</span></div><div className="segmented large"><button className={lang==='en'?'sel':''} onClick={()=>setLang('en')}>English</button><button className={lang==='fr'?'sel':''} onClick={()=>setLang('fr')}>Français</button><button className={lang==='ar'?'sel':''} onClick={()=>setLang('ar')}>العربية</button></div></div><div className="divider"/><div className="section-title"><span><Palette size={16}/> {t.appearance}</span></div><div className="appearance-grid"><button className={theme==='light'?'appearance active':'appearance'} onClick={()=>setTheme('light')}><Sun size={20}/><b>{t.light}</b><span>Clean white canvas</span>{theme==='light'&&<Check size={16}/>}</button><button className={theme==='dark'?'appearance active':'appearance'} onClick={()=>setTheme('dark')}><Moon size={20}/><b>{t.dark}</b><span>Original ELVRA dark</span>{theme==='dark'&&<Check size={16}/>}</button></div></section><section className="panel settings-panel"><div className="section-title"><span><LockKeyhole size={16}/> {t.password}</span></div><form className="form-stack" onSubmit={update}><label>{t.newPassword}<input type="password" minLength="6" value={p} onChange={e=>setP(e.target.value)} required/></label><label>{t.confirmPassword}<input type="password" minLength="6" value={c} onChange={e=>setC(e.target.value)} required/></label><button className="primary-btn"><Check size={17}/>{t.updatePassword}</button></form>{msg&&<div className="success-box">{msg}</div>}{err&&<div className="error-box">{err}</div>}<div className="security-callout"><LockKeyhole size={17}/><div><b>Supabase Auth</b><span>{t.secure}</span></div></div></section></div></main></Layout>
}
